
/*********************************************************************
                        Table FWC_Voter
                   PrimaryKeys and ForeinKeys
*********************************************************************/
CREATE TABLE Voter (
       ID    NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1)  NOT NULL PRIMARY KEY,
       First_Name  VARCHAR2(20), -- Name
       Last_Name  VARCHAR2(20), -- Surname
       Phone VARCHAR2(20),
       Chat_ID NUMBER NOT NULL, -- Personal ID between User an Bot
       LANGUAGE VARCHAR2(2), -- ro-(Romain)  ru-(Russian)
       Voted_Team NUMBER, -- ID Team what User think to win in final
       Date_Voted_Team DATE -- Date when User has select team
       --Points NUMBER -- Total number of points
       
                
)
/*********************************************************************
                        Table FWC_Match
                   PrimaryKeys and ForeinKeys
*********************************************************************/
/
CREATE TABLE Match (
       ID    NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL PRIMARY KEY,
       First_Team_ID NUMBER, -- Team name
       Second_Team_ID NUMBER, -- Team name
       Start_Time DATE, -- Start date when match is 
       First_Team_Score NUMBER,  -- FirstTeam score 
       Second_Team_Score NUMBER -- SecondTeam score
       --Status VARCHAR2(20) -- Active / Inactive / 
)



/*********************************************************************
                        Table FWC_Countries
                   PrimaryKeys and ForeinKeys
*********************************************************************/
/
CREATE TABLE Teams (
       ID    NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL PRIMARY KEY,
       Team_Name VARCHAR2(50) -- Player name
)
/*********************************************************************
                        Table FWC_Prognose
                   PrimaryKeys and ForeinKeys
*********************************************************************/
/
CREATE TABLE Prognose (
       ID    NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL PRIMARY KEY,
       Voter_ID NUMBER NOT NULL, -- Voter ID
       Match_ID NUMBER, -- Match ID
       Score_Team1 NUMBER, -- 
       Score_Team2 NUMBER, -- 
       Prognosed_Team NUMBER, -- player who has get a goal
       Prognosed_Player NUMBER, -- player who has get a goal
       Prognosed_Date DATE DEFAULT SYSDATE,  -- Date when Voter has prognose team
       Prognosed_Type NUMBER
       
)
/*********************************************************************
                        Table FWC_History
                   PrimaryKeys and ForeinKeys
*********************************************************************/
/
CREATE TABLE prognose_history (
       ID    NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL PRIMARY KEY,
       Voter_ID NUMBER NOT NULL, -- Voter ID
       Match_ID NUMBER, -- Match ID
       Score_Team1 NUMBER, -- 
       Score_Team2 NUMBER, -- 
       Prognosed_Team NUMBER, -- player who has get a goal
       Prognosed_Player NUMBER, -- player who has get a goal
       Prognosed_Date DATE DEFAULT SYSDATE,  -- Date when Voter has prognose team
       Prognosed_Type NUMBER
       
)
/*********************************************************************
                        Table FWC_Players
                   PrimaryKeys and ForeinKeys
*********************************************************************/
/
CREATE TABLE Players (
       ID    NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL PRIMARY KEY,
       Team_ID NUMBER, -- Voter ID
       Player_Name VARCHAR2(50) -- player
       
)
/
/*********************************************************************
                        Table FWC_Players
                   PrimaryKeys and ForeinKeys
*********************************************************************/



CREATE TABLE Player_Goals (
       ID    NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL PRIMARY KEY,
       Player_ID NUMBER, -- 
       Match_ID NUMBER, --  
       Goals NUMBER -- 
       
)
/
/*********************************************************************
                        Table FWC_Loggs
                   PrimaryKeys and ForeinKeys
*********************************************************************/
CREATE TABLE Loggs(ID    NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1)  NOT NULL PRIMARY KEY,
                   UserID NUMBER,
                   UserMessage VARCHAR2(1000),
                   UserCallbackData VARCHAR2(50),
                   ThrowedExceptions VARCHAR2(4000),
                   LoggType NUMBER, -- 1 = UserMessage 2 = CallbackData 3 = Any Errors 
                   LoggDate DATE DEFAULT SYSDATE
)
                              
/*********************************************************************
                        Table FWC_Languages
                   PrimaryKeys and ForeinKeys
                   
CREATE TABLE Languages (
       ID    NUMBER NOT NULL PRIMARY KEY,
       Language_Text VARCHAR2(300)
)
/
*********************************************************************/




/*********************************************************************
                        Add ForeinKeys
*********************************************************************/

/*
ALTER TABLE Voter ADD CONSTRAINT fk_VoterT FOREIGN KEY (Voted_Team) REFERENCES Teams(ID);
ALTER TABLE Match ADD CONSTRAINT fk_MatchTF FOREIGN KEY (First_Team_ID) REFERENCES Teams(ID);
ALTER TABLE Match ADD CONSTRAINT fk_MatchTS FOREIGN KEY (Second_Team_ID) REFERENCES Teams(ID);
ALTER TABLE Prognose ADD CONSTRAINT fk_PrognoseV FOREIGN KEY (Voter_ID) REFERENCES Voter(ID);
ALTER TABLE Prognose ADD CONSTRAINT fk_PrognoseM FOREIGN KEY (Match_ID) REFERENCES Match(ID);
ALTER TABLE Prognose ADD CONSTRAINT fk_PrognoseP FOREIGN KEY (Prognosed_Player) REFERENCES Players(ID);
ALTER TABLE Prognose ADD CONSTRAINT fk_PrognoseT FOREIGN KEY (Prognosed_Team) REFERENCES Teams(ID);
ALTER TABLE Prognose_history ADD CONSTRAINT fk_Prognose_historyV FOREIGN KEY (Voter_ID) REFERENCES Voter(ID);
ALTER TABLE Prognose_history ADD CONSTRAINT fk_Prognose_historyM FOREIGN KEY (Match_ID) REFERENCES Match(ID);
ALTER TABLE Prognose_history ADD CONSTRAINT fk_Prognose_historyP FOREIGN KEY (Prognosed_Player) REFERENCES Players(ID);
ALTER TABLE Prognose_history ADD CONSTRAINT fk_Prognose_historyT FOREIGN KEY (Prognosed_Team) REFERENCES Teams(ID);
ALTER TABLE Players ADD CONSTRAINT fk_PlayersT FOREIGN KEY (Team_ID) REFERENCES Teams(ID);
ALTER TABLE Player_Goals ADD CONSTRAINT fk_PlayerGoalsP FOREIGN KEY (Player_ID) REFERENCES Players(ID);
ALTER TABLE Player_Goals ADD CONSTRAINT fk_PlayerGoalsM FOREIGN KEY (Match_ID) REFERENCES Match(ID);



ALTER TABLE Voter DROP CONSTRAINT fk_VoterT;
ALTER TABLE Match DROP CONSTRAINT fk_MatchTF;
ALTER TABLE Match DROP CONSTRAINT fk_MatchTS;
ALTER TABLE Prognose DROP CONSTRAINT fk_PrognoseV;
ALTER TABLE Prognose DROP CONSTRAINT fk_PrognoseM;
ALTER TABLE Prognose DROP CONSTRAINT fk_PrognoseP;
ALTER TABLE Prognose DROP CONSTRAINT fk_PrognoseT;
ALTER TABLE Prognose DROP CONSTRAINT fk_Prognose_historyV;
ALTER TABLE Prognose DROP CONSTRAINT fk_Prognose_historyM;
ALTER TABLE Prognose DROP CONSTRAINT fk_Prognose_historyP;
ALTER TABLE Prognose DROP CONSTRAINT fk_Prognose_historyT;
ALTER TABLE Players DROP CONSTRAINT fk_PlayersT;
ALTER TABLE Player_Goals DROP CONSTRAINT fk_PlayerGoalsP;
ALTER TABLE Player_Goals DROP CONSTRAINT fk_PlayerGoalsM;
*/




/*********************************************************************
                      Drop Tables and ForeinKeys
*********************************************************************/
/*
DROP TABLE Voter CASCADE CONSTRAINTS;
DROP TABLE Match CASCADE CONSTRAINTS;
DROP TABLE Teams CASCADE CONSTRAINTS;
DROP TABLE Prognose CASCADE CONSTRAINTS;
DROP TABLE prognose_history CASCADE CONSTRAINTS;
DROP TABLE Players CASCADE CONSTRAINTS;
DROP TABLE Player_Goals CASCADE CONSTRAINTS;
DROP TABLE Languages CASCADE CONSTRAINTS;
*/
