/*********************************************************************
                        Insert Values into Tables
*********************************************************************/
-- Languages (ID (100- romain 200 - Russian), Text);
INSERT INTO Languages VALUES (100, 'Inapoi');
INSERT INTO Languages VALUES (200, 'Назад');
INSERT INTO Languages VALUES (101, 'Meniu');
INSERT INTO Languages VALUES (201, 'Меню');

INSERT INTO Teams VALUES (DEFAULT, 'Qatar'         );
INSERT INTO Teams VALUES (DEFAULT, 'Ecuador'       );
INSERT INTO Teams VALUES (DEFAULT, 'Senegal'       );
INSERT INTO Teams VALUES (DEFAULT, 'Netherlands'   );
INSERT INTO Teams VALUES (DEFAULT, 'England'       );
INSERT INTO Teams VALUES (DEFAULT, 'IR-Iran'       );
INSERT INTO Teams VALUES (DEFAULT, 'USA'           );
INSERT INTO Teams VALUES (DEFAULT, 'Wales'         );
INSERT INTO Teams VALUES (DEFAULT, 'Argentina'     );
INSERT INTO Teams VALUES (DEFAULT, 'Saudi-Arabia'  );
INSERT INTO Teams VALUES (DEFAULT, 'Mexico'        );
INSERT INTO Teams VALUES (DEFAULT, 'Poland'        );
INSERT INTO Teams VALUES (DEFAULT, 'France'        );
INSERT INTO Teams VALUES (DEFAULT, 'Denmark'       );
INSERT INTO Teams VALUES (DEFAULT, 'Tunisia'       );
INSERT INTO Teams VALUES (DEFAULT, 'Australia'     );
INSERT INTO Teams VALUES (DEFAULT, 'Spain'         );
INSERT INTO Teams VALUES (DEFAULT, 'Germany'       );
INSERT INTO Teams VALUES (DEFAULT, 'Japan'         );
INSERT INTO Teams VALUES (DEFAULT, 'Costa-Rica'    );
INSERT INTO Teams VALUES (DEFAULT, 'Belgium'       );
INSERT INTO Teams VALUES (DEFAULT, 'Canada'        );
INSERT INTO Teams VALUES (DEFAULT, 'Morocco'       );
INSERT INTO Teams VALUES (DEFAULT, 'Croatia'       );
INSERT INTO Teams VALUES (DEFAULT, 'Brazil'        );
INSERT INTO Teams VALUES (DEFAULT, 'Serbia'        );
INSERT INTO Teams VALUES (DEFAULT, 'Switzerland'   );
INSERT INTO Teams VALUES (DEFAULT, 'Cameroon'      );
INSERT INTO Teams VALUES (DEFAULT, 'Portugal'      );
INSERT INTO Teams VALUES (DEFAULT, 'Ghana'         );
INSERT INTO Teams VALUES (DEFAULT, 'Uruguay'       );
INSERT INTO Teams VALUES (DEFAULT, 'Korea-Republic');

INSERT INTO Players VALUES (DEFAULT, 1, 'Saad Al Sheeb'       );
INSERT INTO Players VALUES (DEFAULT, 1, 'Yousef Hassan'       );
INSERT INTO Players VALUES (DEFAULT, 1, 'Meshaal Barsham'     );
INSERT INTO Players VALUES (DEFAULT, 1, 'Salah Zakaria'       );
INSERT INTO Players VALUES (DEFAULT, 1, 'Ró-Ró'           );
INSERT INTO Players VALUES (DEFAULT, 1, 'Abdelkarim Hassan'     );
INSERT INTO Players VALUES (DEFAULT, 1, 'Tarek Salman'        );
INSERT INTO Players VALUES (DEFAULT, 1, 'Musab Kheder'        );
INSERT INTO Players VALUES (DEFAULT, 1, 'Homam Ahmed'       );
INSERT INTO Players VALUES (DEFAULT, 1, 'Bassam Al-Rawi'      );
INSERT INTO Players VALUES (DEFAULT, 1, 'Boualem Khoukhi'     );
INSERT INTO Players VALUES (DEFAULT, 1, 'Mohammed Emad'       );
INSERT INTO Players VALUES (DEFAULT, 1, 'Jassem Gaber'        );
INSERT INTO Players VALUES (DEFAULT, 1, 'Mohammed Waad'       );
INSERT INTO Players VALUES (DEFAULT, 1, 'Abdulaziz Hatem'     );
INSERT INTO Players VALUES (DEFAULT, 1, 'Ali Assadalla'       );
INSERT INTO Players VALUES (DEFAULT, 1, 'Karim Boudiaf'       );
INSERT INTO Players VALUES (DEFAULT, 1, 'Ahmed Fadhel'        );
INSERT INTO Players VALUES (DEFAULT, 1, 'Mostafa Tarek'       );
INSERT INTO Players VALUES (DEFAULT, 1, 'Abdelrahman Moustafa'    );
INSERT INTO Players VALUES (DEFAULT, 1, 'Osama Al-Tairi'      );
INSERT INTO Players VALUES (DEFAULT, 1, 'Ahmed Alaaeldin'     );
INSERT INTO Players VALUES (DEFAULT, 1, 'Mohammed Muntari'      );
INSERT INTO Players VALUES (DEFAULT, 1, 'Hassan Al-Haydos'      );
INSERT INTO Players VALUES (DEFAULT, 1, 'Akram Afif'        );
INSERT INTO Players VALUES (DEFAULT, 1, 'Ismaeel Mohammad'      );
INSERT INTO Players VALUES (DEFAULT, 1, 'Khalid Muneer'       );
INSERT INTO Players VALUES (DEFAULT, 1, 'Almoez Ali'        );
INSERT INTO Players VALUES (DEFAULT, 1, 'Naif Al-Hadhrami'      );
INSERT INTO Players VALUES (DEFAULT, 1, 'Yusuf Abdurisag'     );

INSERT INTO Players VALUES (DEFAULT, 2, 'Alexander Domínguez'   );
INSERT INTO Players VALUES (DEFAULT, 2, 'Hernán Galíndez'     );
INSERT INTO Players VALUES (DEFAULT, 2, 'Moisés Ramírez'      );
INSERT INTO Players VALUES (DEFAULT, 2, 'Gonzalo Valle'       );
INSERT INTO Players VALUES (DEFAULT, 2, 'Pervis Estupiñán'      );
INSERT INTO Players VALUES (DEFAULT, 2, 'Ángelo Preciado'     );
INSERT INTO Players VALUES (DEFAULT, 2, 'Piero Hincapié'      );
INSERT INTO Players VALUES (DEFAULT, 2, 'Xavier Arreaga'      );
INSERT INTO Players VALUES (DEFAULT, 2, 'Byron Castillo'      );
INSERT INTO Players VALUES (DEFAULT, 2, 'Diego Palacios'      );
INSERT INTO Players VALUES (DEFAULT, 2, 'Fernando León'       );
INSERT INTO Players VALUES (DEFAULT, 2, 'Jackson Porozo'      );
INSERT INTO Players VALUES (DEFAULT, 2, 'William Pacho'       );
INSERT INTO Players VALUES (DEFAULT, 2, 'Ángel Mena'        );
INSERT INTO Players VALUES (DEFAULT, 2, 'Carlos Gruezo'       );
INSERT INTO Players VALUES (DEFAULT, 2, 'Jhegson Méndez'      );
INSERT INTO Players VALUES (DEFAULT, 2, 'Gonzalo Plata'       );
INSERT INTO Players VALUES (DEFAULT, 2, 'Moisés Caicedo'      );
INSERT INTO Players VALUES (DEFAULT, 2, 'Romario Ibarra'      );
INSERT INTO Players VALUES (DEFAULT, 2, 'Alan Franco'       );
INSERT INTO Players VALUES (DEFAULT, 2, 'José Cifuentes'      );
INSERT INTO Players VALUES (DEFAULT, 2, 'Jeremy Sarmiento'      );
INSERT INTO Players VALUES (DEFAULT, 2, 'Nilson Angulo'       );
INSERT INTO Players VALUES (DEFAULT, 2, 'Patrickson Delgado'    );
INSERT INTO Players VALUES (DEFAULT, 2, 'Anthony Valencia'      );
INSERT INTO Players VALUES (DEFAULT, 2, 'Enner Valencia'      );
INSERT INTO Players VALUES (DEFAULT, 2, 'Michael Estrada'     );
INSERT INTO Players VALUES (DEFAULT, 2, 'Djorkaeff Reasco'      );

INSERT INTO Players VALUES (DEFAULT, 3,'Seny Dieng'       );
INSERT INTO Players VALUES (DEFAULT, 3,'Alfred Gomis'     );
INSERT INTO Players VALUES (DEFAULT, 3,'Mory Diaw'        );
INSERT INTO Players VALUES (DEFAULT, 3,'Formose Mendy'      );
INSERT INTO Players VALUES (DEFAULT, 3,'Kalidou Koulibaly'    );
INSERT INTO Players VALUES (DEFAULT, 3,'Pape Abou Cissé'    );
INSERT INTO Players VALUES (DEFAULT, 3,'Abdou Diallo'     );
INSERT INTO Players VALUES (DEFAULT, 3,'Fodé Ballo-Touré'   );
INSERT INTO Players VALUES (DEFAULT, 3,'Ismail Jakobs'      );
INSERT INTO Players VALUES (DEFAULT, 3,'Moussa Niakhaté'    );
INSERT INTO Players VALUES (DEFAULT, 3,'Idrissa Gueye'      );
INSERT INTO Players VALUES (DEFAULT, 3,'Nampalys Mendy'     );
INSERT INTO Players VALUES (DEFAULT, 3,'Cheikhou Kouyaté'   );
INSERT INTO Players VALUES (DEFAULT, 3,'Pathé Ciss'       );
INSERT INTO Players VALUES (DEFAULT, 3,'Krépin Diatta'      );
INSERT INTO Players VALUES (DEFAULT, 3,'Pape Matar Sarr'    );
INSERT INTO Players VALUES (DEFAULT, 3,'Moustapha Name'     );
INSERT INTO Players VALUES (DEFAULT, 3,'Mamadou Loum'     );
INSERT INTO Players VALUES (DEFAULT, 3,'Pape Gueye'       );
INSERT INTO Players VALUES (DEFAULT, 3,'Boulaye Dia'      );
INSERT INTO Players VALUES (DEFAULT, 3,'Sadio Mané'       );
INSERT INTO Players VALUES (DEFAULT, 3,'Ismaïla Sarr'     );
INSERT INTO Players VALUES (DEFAULT, 3,'Bamba Dieng'      );
INSERT INTO Players VALUES (DEFAULT, 3,'Iliman Ndiaye'      );
INSERT INTO Players VALUES (DEFAULT, 3,'Nicolas Jackson'    );
INSERT INTO Players VALUES (DEFAULT, 3,'Demba Seck'       );
INSERT INTO Players VALUES (DEFAULT, 3,'Habib Diallo'     );

INSERT INTO Players VALUES (DEFAULT, 4, 'Remko Pasveer'       );
INSERT INTO Players VALUES (DEFAULT, 4, 'Jasper Cillessen'      );
INSERT INTO Players VALUES (DEFAULT, 4, 'Mark Flekken'        );
INSERT INTO Players VALUES (DEFAULT, 4, 'Andries Noppert'     );
INSERT INTO Players VALUES (DEFAULT, 4, 'Jurriën Timber'      );
INSERT INTO Players VALUES (DEFAULT, 4, 'Matthijs de Ligt'      );
INSERT INTO Players VALUES (DEFAULT, 4, 'Virgil van Dijk'     );
INSERT INTO Players VALUES (DEFAULT, 4, 'Nathan Aké'        );
INSERT INTO Players VALUES (DEFAULT, 4, 'Stefan de Vrij'      );
INSERT INTO Players VALUES (DEFAULT, 4, 'Devyne Rensch'       );
INSERT INTO Players VALUES (DEFAULT, 4, 'Tyrell Malacia'      );
INSERT INTO Players VALUES (DEFAULT, 4, 'Daley Blind'       );
INSERT INTO Players VALUES (DEFAULT, 4, 'Denzel Dumfries'     );
INSERT INTO Players VALUES (DEFAULT, 4, 'Bruno Martins Indi'    );
INSERT INTO Players VALUES (DEFAULT, 4, 'Steven Berghuis'     );
INSERT INTO Players VALUES (DEFAULT, 4, 'Davy Klaassen'       );
INSERT INTO Players VALUES (DEFAULT, 4, 'Marten de Roon'      );
INSERT INTO Players VALUES (DEFAULT, 4, 'Kenneth Taylor'      );
INSERT INTO Players VALUES (DEFAULT, 4, 'Ryan Gravenberch'      );
INSERT INTO Players VALUES (DEFAULT, 4, 'Frenkie de Jong'     );
INSERT INTO Players VALUES (DEFAULT, 4, 'Steven Bergwijn'     );
INSERT INTO Players VALUES (DEFAULT, 4, 'Cody Gakpo'        );
INSERT INTO Players VALUES (DEFAULT, 4, 'Vincent Janssen'     );
INSERT INTO Players VALUES (DEFAULT, 4, 'Memphis Depay'       );
INSERT INTO Players VALUES (DEFAULT, 4, 'Wout Weghorst'       );

INSERT INTO Players VALUES (DEFAULT, 5, 'Nick Pope'         );
INSERT INTO Players VALUES (DEFAULT, 5, 'Aaron Ramsdale'      );
INSERT INTO Players VALUES (DEFAULT, 5, 'Dean Henderson'      );
INSERT INTO Players VALUES (DEFAULT, 5, 'Reece James'       );
INSERT INTO Players VALUES (DEFAULT, 5, 'Luke Shaw'         );
INSERT INTO Players VALUES (DEFAULT, 5, 'John Stones'       );
INSERT INTO Players VALUES (DEFAULT, 5, 'Eric Dier'         );
INSERT INTO Players VALUES (DEFAULT, 5, 'Harry Maguire'       );
INSERT INTO Players VALUES (DEFAULT, 5, 'Kieran Trippier'     );
INSERT INTO Players VALUES (DEFAULT, 5, 'Kyle Walker'       );
INSERT INTO Players VALUES (DEFAULT, 5, 'Conor Coady'       );
INSERT INTO Players VALUES (DEFAULT, 5, 'Marc Guéhi'        );
INSERT INTO Players VALUES (DEFAULT, 5, 'Ben Chilwell'        );
INSERT INTO Players VALUES (DEFAULT, 5, 'Trent Alexander-Arnold'  );
INSERT INTO Players VALUES (DEFAULT, 5, 'Fikayo Tomori'       );
INSERT INTO Players VALUES (DEFAULT, 5, 'Declan Rice'       );
INSERT INTO Players VALUES (DEFAULT, 5, 'Jude Bellingham'     );
INSERT INTO Players VALUES (DEFAULT, 5, 'Jordan Henderson'      );
INSERT INTO Players VALUES (DEFAULT, 5, 'Mason Mount'       );
INSERT INTO Players VALUES (DEFAULT, 5, 'James Ward-Prowse'     );
INSERT INTO Players VALUES (DEFAULT, 5, 'Harry Kane'        );
INSERT INTO Players VALUES (DEFAULT, 5, 'Raheem Sterling'     );
INSERT INTO Players VALUES (DEFAULT, 5, 'Phil Foden'        );
INSERT INTO Players VALUES (DEFAULT, 5, 'Bukayo Saka'       );
INSERT INTO Players VALUES (DEFAULT, 5, 'Ivan Toney'        );
INSERT INTO Players VALUES (DEFAULT, 5, 'Tammy Abraham'       );
INSERT INTO Players VALUES (DEFAULT, 5, 'Jarrod Bowen'        );

INSERT INTO Players VALUES (DEFAULT, 6, 'Alireza Beiranvand'            );
INSERT INTO Players VALUES (DEFAULT, 6, 'Hossein Hosseini'              );
INSERT INTO Players VALUES (DEFAULT, 6, 'Mohammad Reza Akhbari'           );
INSERT INTO Players VALUES (DEFAULT, 6, 'Payam Niazmand'              );
INSERT INTO Players VALUES (DEFAULT, 6, 'Morteza Pouraliganji'            );
INSERT INTO Players VALUES (DEFAULT, 6, 'Ramin Rezaeian'              );
INSERT INTO Players VALUES (DEFAULT, 6, 'Rouzbeh Cheshmi'             );
INSERT INTO Players VALUES (DEFAULT, 6, 'Omid Noorafkan'              );
INSERT INTO Players VALUES (DEFAULT, 6, 'Abolfazl Jalali'             );
INSERT INTO Players VALUES (DEFAULT, 6, 'Armin Sohrabian'             );
INSERT INTO Players VALUES (DEFAULT, 6, 'Saman Fallah'                );
INSERT INTO Players VALUES (DEFAULT, 6, 'Vahid Amiri'               );
INSERT INTO Players VALUES (DEFAULT, 6, 'Mehdi Torabi'                );
INSERT INTO Players VALUES (DEFAULT, 6, 'Milad Sarlak'                );
INSERT INTO Players VALUES (DEFAULT, 6, 'Mehdi Mehdipour'             );
INSERT INTO Players VALUES (DEFAULT, 6, 'Mohammad Khodabandelou'          );
INSERT INTO Players VALUES (DEFAULT, 6, 'Mohammad Mohebi'             );

INSERT INTO Players VALUES (DEFAULT, 7, 'Matt Turner'             );
INSERT INTO Players VALUES (DEFAULT, 7, 'Ethan Horvath'               );
INSERT INTO Players VALUES (DEFAULT, 7, 'Sean Johnson'                );
INSERT INTO Players VALUES (DEFAULT, 7, 'Sergiño Dest'                );
INSERT INTO Players VALUES (DEFAULT, 7, 'Walker Zimmerman'              );
INSERT INTO Players VALUES (DEFAULT, 7, 'Aaron Long'              );
INSERT INTO Players VALUES (DEFAULT, 7, 'Sam Vines'                 );
INSERT INTO Players VALUES (DEFAULT, 7, 'Erik Palmer-Brown'             );
INSERT INTO Players VALUES (DEFAULT, 7, 'Mark McKenzie'               );
INSERT INTO Players VALUES (DEFAULT, 7, 'DeAndre Yedlin'            );
INSERT INTO Players VALUES (DEFAULT, 7, 'Joe Scally'              );
INSERT INTO Players VALUES (DEFAULT, 7, 'Tyler Adams'             );
INSERT INTO Players VALUES (DEFAULT, 7, 'Weston McKennie'           );
INSERT INTO Players VALUES (DEFAULT, 7, 'Luca de la Torre'              );
INSERT INTO Players VALUES (DEFAULT, 7, 'Johnny Cardoso'            );
INSERT INTO Players VALUES (DEFAULT, 7, 'Malik Tillman'               );
INSERT INTO Players VALUES (DEFAULT, 7, 'Kellyn Acosta'               );
INSERT INTO Players VALUES (DEFAULT, 7, 'Paul Arriola'                );
INSERT INTO Players VALUES (DEFAULT, 7, 'Jesús Ferreira'            );
INSERT INTO Players VALUES (DEFAULT, 7, 'Christian Pulisic'             );
INSERT INTO Players VALUES (DEFAULT, 7, 'Brenden Aaronson'              );
INSERT INTO Players VALUES (DEFAULT, 7, 'Jordan Morris'               );
INSERT INTO Players VALUES (DEFAULT, 7, 'Ricardo Pepi'                );
INSERT INTO Players VALUES (DEFAULT, 7, 'Giovanni Reyna'            );
INSERT INTO Players VALUES (DEFAULT, 7, 'Josh Sargent'                );

INSERT INTO Players VALUES (DEFAULT, 8, 'Wayne Hennessey'       );
INSERT INTO Players VALUES (DEFAULT, 8, 'Danny Ward'          );
INSERT INTO Players VALUES (DEFAULT, 8, 'Tom King'            );
INSERT INTO Players VALUES (DEFAULT, 8, 'Chris Gunter'          );
INSERT INTO Players VALUES (DEFAULT, 8, 'Connor Roberts'        );
INSERT INTO Players VALUES (DEFAULT, 8, 'Joe Rodon'           );
INSERT INTO Players VALUES (DEFAULT, 8, 'Neco Williams'         );
INSERT INTO Players VALUES (DEFAULT, 8, 'Rhys Norrington-Davies'    );
INSERT INTO Players VALUES (DEFAULT, 8, 'Ben Cabango'         );
INSERT INTO Players VALUES (DEFAULT, 8, 'Jonny Williams'        );
INSERT INTO Players VALUES (DEFAULT, 8, 'Joe Morrell'         );
INSERT INTO Players VALUES (DEFAULT, 8, 'Matthew Smith'         );
INSERT INTO Players VALUES (DEFAULT, 8, 'Dylan Levitt'          );
INSERT INTO Players VALUES (DEFAULT, 8, 'Rubin Colwill'         );
INSERT INTO Players VALUES (DEFAULT, 8, 'Sorba Thomas'          );
INSERT INTO Players VALUES (DEFAULT, 8, 'Wes Burns'           );
INSERT INTO Players VALUES (DEFAULT, 8, 'Jordan James'          );
INSERT INTO Players VALUES (DEFAULT, 8, 'Gareth Bale'         );
INSERT INTO Players VALUES (DEFAULT, 8, 'Daniel James'          );
INSERT INTO Players VALUES (DEFAULT, 8, 'Kieffer Moore'         );
INSERT INTO Players VALUES (DEFAULT, 8, 'Tyler Roberts'         );
INSERT INTO Players VALUES (DEFAULT, 8, 'Brennan Johnson'       );
INSERT INTO Players VALUES (DEFAULT, 8, 'Mark Harris'         );

INSERT INTO Players VALUES (DEFAULT, 9, 'Franco Armani'       );
INSERT INTO Players VALUES (DEFAULT, 9, 'Gerónimo Rulli'      );
INSERT INTO Players VALUES (DEFAULT, 9, 'Emiliano Martínez'     );
INSERT INTO Players VALUES (DEFAULT, 9, 'Facundo Medina'      );
INSERT INTO Players VALUES (DEFAULT, 9, 'Nicolás Tagliafico'    );
INSERT INTO Players VALUES (DEFAULT, 9, 'Gonzalo Montiel'     );
INSERT INTO Players VALUES (DEFAULT, 9, 'Germán Pezzella'     );
INSERT INTO Players VALUES (DEFAULT, 9, 'Cristian Romero'     );
INSERT INTO Players VALUES (DEFAULT, 9, 'Nehuén Pérez'        );
INSERT INTO Players VALUES (DEFAULT, 9, 'Nicolás Otamendi'      );
INSERT INTO Players VALUES (DEFAULT, 9, 'Lisandro Martínez'     );
INSERT INTO Players VALUES (DEFAULT, 9, 'Nahuel Molina'       );
INSERT INTO Players VALUES (DEFAULT, 9, 'Leandro Paredes'     );
INSERT INTO Players VALUES (DEFAULT, 9, 'Rodrigo De Paul'     );
INSERT INTO Players VALUES (DEFAULT, 9, 'Thiago Almada'       );
INSERT INTO Players VALUES (DEFAULT, 9, 'Ángel Di María'      );
INSERT INTO Players VALUES (DEFAULT, 9, 'Enzo Fernández'      );
INSERT INTO Players VALUES (DEFAULT, 9, 'Alexis Mac Allister'   );
INSERT INTO Players VALUES (DEFAULT, 9, 'Guido Rodríguez'     );
INSERT INTO Players VALUES (DEFAULT, 9, 'Giovani Lo Celso'      );
INSERT INTO Players VALUES (DEFAULT, 9, 'Julián Álvarez'      );
INSERT INTO Players VALUES (DEFAULT, 9, 'Lionel Messi'        );
INSERT INTO Players VALUES (DEFAULT, 9, 'Joaquín Correa'      );
INSERT INTO Players VALUES (DEFAULT, 9, 'Paulo Dybala'        );
INSERT INTO Players VALUES (DEFAULT, 9, 'Lautaro Martínez'      );
INSERT INTO Players VALUES (DEFAULT, 9, 'Ángel Correa'        );

INSERT INTO Players VALUES (DEFAULT, 10, 'Mohammed Al-Owais'          );
INSERT INTO Players VALUES (DEFAULT, 10, 'Fawaz Al-Qarni'           );
INSERT INTO Players VALUES (DEFAULT, 10, 'Mohammed Al Rubaie'         );
INSERT INTO Players VALUES (DEFAULT, 10, 'Nawaf Al-Aqidi'           );
INSERT INTO Players VALUES (DEFAULT, 10, 'Yasser Al-Shahrani'         );
INSERT INTO Players VALUES (DEFAULT, 10, 'Mohammed Al-Breik'          );
INSERT INTO Players VALUES (DEFAULT, 10, 'Ali Al-Bulaihi'           );
INSERT INTO Players VALUES (DEFAULT, 10, 'Sultan Al-Ghanam'           );
INSERT INTO Players VALUES (DEFAULT, 10, 'Saud Abdulhamid'            );
INSERT INTO Players VALUES (DEFAULT, 10, 'Abdulelah Al-Amri'          );
INSERT INTO Players VALUES (DEFAULT, 10, 'Hassan Tambakti'            );
INSERT INTO Players VALUES (DEFAULT, 10, 'Abdullah Madu'            );
INSERT INTO Players VALUES (DEFAULT, 10, 'Ahmed Bamsaud'            );
INSERT INTO Players VALUES (DEFAULT, 10, 'Fahad Al-Muwallad'          );
INSERT INTO Players VALUES (DEFAULT, 10, 'Salman Al-Faraj'            );
INSERT INTO Players VALUES (DEFAULT, 10, 'Salem Al-Dawsari'           );
INSERT INTO Players VALUES (DEFAULT, 10, 'Nawaf Al-Abed'            );
INSERT INTO Players VALUES (DEFAULT, 10, 'Abdullah Otayf'           );
INSERT INTO Players VALUES (DEFAULT, 10, 'Hattan Bahebri'           );
INSERT INTO Players VALUES (DEFAULT, 10, 'Mohamed Kanno'            );
INSERT INTO Players VALUES (DEFAULT, 10, 'Abdulellah Al-Malki'        );
INSERT INTO Players VALUES (DEFAULT, 10, 'Sami Al-Najei'            );
INSERT INTO Players VALUES (DEFAULT, 10, 'Ali Al-Hassan'            );
INSERT INTO Players VALUES (DEFAULT, 10, 'Nasser Al-Dawsari'          );
INSERT INTO Players VALUES (DEFAULT, 10, 'Ayman Yahya'              );
INSERT INTO Players VALUES (DEFAULT, 10, 'Abdulrahman Al-Aboud'         );
INSERT INTO Players VALUES (DEFAULT, 10, 'Riyadh Sharahili'           );
INSERT INTO Players VALUES (DEFAULT, 10, 'Firas Al-Buraikan'        );
INSERT INTO Players VALUES (DEFAULT, 10, 'Abdullah Al-Hamdan'       );
INSERT INTO Players VALUES (DEFAULT, 10, 'Saleh Al-Shehri'          );
INSERT INTO Players VALUES (DEFAULT, 10, 'Haitham Asiri'          );
INSERT INTO Players VALUES (DEFAULT, 10, 'Abdullah Radif'         );

INSERT INTO Players VALUES (DEFAULT, 11, 'Alfredo Talavera'             );
INSERT INTO Players VALUES (DEFAULT, 11, 'Rodolfo Cota'               );
INSERT INTO Players VALUES (DEFAULT, 11, 'Guillermo Ochoa'              );
INSERT INTO Players VALUES (DEFAULT, 11, 'Néstor Araujo'            );
INSERT INTO Players VALUES (DEFAULT, 11, 'César Montes'               );
INSERT INTO Players VALUES (DEFAULT, 11, 'Johan Vásquez'            );
INSERT INTO Players VALUES (DEFAULT, 11, 'Gerardo Arteaga'              );
INSERT INTO Players VALUES (DEFAULT, 11, 'Héctor Moreno'            );
INSERT INTO Players VALUES (DEFAULT, 11, 'Jorge Sánchez'            );
INSERT INTO Players VALUES (DEFAULT, 11, 'Jesús Gallardo'             );
INSERT INTO Players VALUES (DEFAULT, 11, 'Jesús Alberto Angulo'           );
INSERT INTO Players VALUES (DEFAULT, 11, 'Kevin Álvarez'            );
INSERT INTO Players VALUES (DEFAULT, 11, 'Edson Álvarez'            );
INSERT INTO Players VALUES (DEFAULT, 11, 'Luis Romo'              );
INSERT INTO Players VALUES (DEFAULT, 11, 'Carlos Rodríguez'             );
INSERT INTO Players VALUES (DEFAULT, 11, 'Érick Gutiérrez'              );
INSERT INTO Players VALUES (DEFAULT, 11, 'Héctor Herrera'             );
INSERT INTO Players VALUES (DEFAULT, 11, 'Luis Chávez'                );
INSERT INTO Players VALUES (DEFAULT, 11, 'Andrés Guardado'              );
INSERT INTO Players VALUES (DEFAULT, 11, 'Diego Lainez'               );
INSERT INTO Players VALUES (DEFAULT, 11, 'Uriel Antuna'               );
INSERT INTO Players VALUES (DEFAULT, 11, 'Roberto Alvarado'             );
INSERT INTO Players VALUES (DEFAULT, 11, 'Fernando Beltrán'             );
INSERT INTO Players VALUES (DEFAULT, 11, 'Érick Sánchez'            );
INSERT INTO Players VALUES (DEFAULT, 11, 'Orbelín Pineda'             );
INSERT INTO Players VALUES (DEFAULT, 11, 'Raúl Jiménez'               );
INSERT INTO Players VALUES (DEFAULT, 11, 'Alexis Vega'                );
INSERT INTO Players VALUES (DEFAULT, 11, 'Rogelio Funes Mori'           );
INSERT INTO Players VALUES (DEFAULT, 11, 'Henry Martín'               );
INSERT INTO Players VALUES (DEFAULT, 11, 'Hirving Lozano'             );
INSERT INTO Players VALUES (DEFAULT, 11, 'Santiago Giménez'             );

INSERT INTO Players VALUES (DEFAULT, 12, 'Wojciech Szczęsny'            );
INSERT INTO Players VALUES (DEFAULT, 12, 'Łukasz Skorupski'             );
INSERT INTO Players VALUES (DEFAULT, 12, 'Bartłomiej Drągowski'           );
INSERT INTO Players VALUES (DEFAULT, 12, 'Radosław Majecki'             );
INSERT INTO Players VALUES (DEFAULT, 12, 'Robert Gumny'               );
INSERT INTO Players VALUES (DEFAULT, 12, 'Jakub Kiwior'               );
INSERT INTO Players VALUES (DEFAULT, 12, 'Tomasz Kędziora'              );
INSERT INTO Players VALUES (DEFAULT, 12, 'Jan Bednarek'               );
INSERT INTO Players VALUES (DEFAULT, 12, 'Mateusz Wieteska'             );
INSERT INTO Players VALUES (DEFAULT, 12, 'Kamil Glik'               );
INSERT INTO Players VALUES (DEFAULT, 12, 'Bartosz Bereszyński'            );
INSERT INTO Players VALUES (DEFAULT, 12, 'Paweł Dawidowicz'             );
INSERT INTO Players VALUES (DEFAULT, 12, 'Jakub Piotrowski'             );
INSERT INTO Players VALUES (DEFAULT, 12, 'Grzegorz Krychowiak'            );
INSERT INTO Players VALUES (DEFAULT, 12, 'Kamil Grosicki'             );
INSERT INTO Players VALUES (DEFAULT, 12, 'Szymon Żurkowski'             );
INSERT INTO Players VALUES (DEFAULT, 12, 'Michał Skóraś'              );
INSERT INTO Players VALUES (DEFAULT, 12, 'Jakub Kamiński'             );
INSERT INTO Players VALUES (DEFAULT, 12, 'Sebastian Szymański'            );
INSERT INTO Players VALUES (DEFAULT, 12, 'Piotr Zieliński'              );
INSERT INTO Players VALUES (DEFAULT, 12, 'Nicola Zalewski'              );
INSERT INTO Players VALUES (DEFAULT, 12, 'Karol Linetty'              );
INSERT INTO Players VALUES (DEFAULT, 12, 'Mateusz Klich'              );
INSERT INTO Players VALUES (DEFAULT, 12, 'Przemysław Frankowski'          );
INSERT INTO Players VALUES (DEFAULT, 12, 'Arkadiusz Milik'              );
INSERT INTO Players VALUES (DEFAULT, 12, 'Robert Lewandowski'           );
INSERT INTO Players VALUES (DEFAULT, 12, 'Karol Świderski'              );
INSERT INTO Players VALUES (DEFAULT, 12, 'Krzysztof Piątek'             );

INSERT INTO Players VALUES (DEFAULT, 13, 'Alban Lafont'               );
INSERT INTO Players VALUES (DEFAULT, 13, 'Steve Mandanda'             );
INSERT INTO Players VALUES (DEFAULT, 13, 'Alphonse Areola'              );
INSERT INTO Players VALUES (DEFAULT, 13, 'Benjamin Pavard'              );
INSERT INTO Players VALUES (DEFAULT, 13, 'William Saliba'             );
INSERT INTO Players VALUES (DEFAULT, 13, 'Raphaël Varane'             );
INSERT INTO Players VALUES (DEFAULT, 13, 'Jules Koundé'               );
INSERT INTO Players VALUES (DEFAULT, 13, 'Dayot Upamecano'              );
INSERT INTO Players VALUES (DEFAULT, 13, 'Jonathan Clauss'              );
INSERT INTO Players VALUES (DEFAULT, 13, 'Benoît Badiashile'            );
INSERT INTO Players VALUES (DEFAULT, 13, 'Ferland Mendy'              );
INSERT INTO Players VALUES (DEFAULT, 13, 'Adrien Truffert'              );
INSERT INTO Players VALUES (DEFAULT, 13, 'Eduardo Camavinga'            );
INSERT INTO Players VALUES (DEFAULT, 13, 'Aurélien Tchouaméni'            );
INSERT INTO Players VALUES (DEFAULT, 13, 'Christopher Nkunku'           );
INSERT INTO Players VALUES (DEFAULT, 13, 'Matteo Guendouzi'             );
INSERT INTO Players VALUES (DEFAULT, 13, 'Jordan Veretout'              );
INSERT INTO Players VALUES (DEFAULT, 13, 'Youssouf Fofana'              );
INSERT INTO Players VALUES (DEFAULT, 13, 'Antoine Griezmann'            );
INSERT INTO Players VALUES (DEFAULT, 13, 'Olivier Giroud'             );
INSERT INTO Players VALUES (DEFAULT, 13, 'Kylian Mbappé'              );
INSERT INTO Players VALUES (DEFAULT, 13, 'Randal Kolo Muani'            );

INSERT INTO Players VALUES (DEFAULT, 14, 'Kasper Schmeichel'            );
INSERT INTO Players VALUES (DEFAULT, 14, 'Oliver Christensen'           );
INSERT INTO Players VALUES (DEFAULT, 14, 'Frederik Rønnow'              );
INSERT INTO Players VALUES (DEFAULT, 14, 'Joachim Andersen'             );
INSERT INTO Players VALUES (DEFAULT, 14, 'Victor Nelsson'             );
INSERT INTO Players VALUES (DEFAULT, 14, 'Simon Kjær'               );
INSERT INTO Players VALUES (DEFAULT, 14, 'Joakim Mæhle'               );
INSERT INTO Players VALUES (DEFAULT, 14, 'Andreas Christensen'            );
INSERT INTO Players VALUES (DEFAULT, 14, 'Rasmus Kristensen'            );
INSERT INTO Players VALUES (DEFAULT, 14, 'Jens Stryger Larsen'            );
INSERT INTO Players VALUES (DEFAULT, 14, 'Alexander Bah'              );
INSERT INTO Players VALUES (DEFAULT, 14, 'Mathias Jensen'             );
INSERT INTO Players VALUES (DEFAULT, 14, 'Thomas Delaney'             );
INSERT INTO Players VALUES (DEFAULT, 14, 'Christian Eriksen '           );
INSERT INTO Players VALUES (DEFAULT, 14, 'Philip Billing'             );
INSERT INTO Players VALUES (DEFAULT, 14, 'Daniel Wass'                );
INSERT INTO Players VALUES (DEFAULT, 14, 'Pierre-Emile Højbjerg'          );
INSERT INTO Players VALUES (DEFAULT, 14, 'Martin Braithwaite'           );
INSERT INTO Players VALUES (DEFAULT, 14, 'Andreas Skov Olsen'           );
INSERT INTO Players VALUES (DEFAULT, 14, 'Kasper Dolberg'             );
INSERT INTO Players VALUES (DEFAULT, 14, 'Mikkel Damsgaard'             );
INSERT INTO Players VALUES (DEFAULT, 14, 'Jesper Lindstrøm'             );
INSERT INTO Players VALUES (DEFAULT, 14, 'Rasmus Højlund'             );

INSERT INTO Players VALUES (DEFAULT, 15, 'Mohamed Sedki Debchi'           );
INSERT INTO Players VALUES (DEFAULT, 15, 'Aymen Dahmen'               );
INSERT INTO Players VALUES (DEFAULT, 15, 'Bechir Ben Saïd'              );
INSERT INTO Players VALUES (DEFAULT, 15, 'Bilel Ifa'                );
INSERT INTO Players VALUES (DEFAULT, 15, 'Montassar Talbi'              );
INSERT INTO Players VALUES (DEFAULT, 15, 'Ali Abdi'                 );
INSERT INTO Players VALUES (DEFAULT, 15, 'Nader Ghandri'              );
INSERT INTO Players VALUES (DEFAULT, 15, 'Dylan Bronn'                );
INSERT INTO Players VALUES (DEFAULT, 15, 'Mortadha Ben Ouanes'            );
INSERT INTO Players VALUES (DEFAULT, 15, 'Ali Maâloul'                );
INSERT INTO Players VALUES (DEFAULT, 15, 'Omar Rekik'               );
INSERT INTO Players VALUES (DEFAULT, 15, 'Mohamed Dräger'             );
INSERT INTO Players VALUES (DEFAULT, 15, 'Hamza Mathlouthi'             );
INSERT INTO Players VALUES (DEFAULT, 15, 'Rami Kaib'                );
INSERT INTO Players VALUES (DEFAULT, 15, 'Yan Valery'               );
INSERT INTO Players VALUES (DEFAULT, 15, 'Saîf-Eddine Khaoui'           );
INSERT INTO Players VALUES (DEFAULT, 15, 'Ferjani Sassi'              );
INSERT INTO Players VALUES (DEFAULT, 15, 'Hannibal Mejbri'              );
INSERT INTO Players VALUES (DEFAULT, 15, 'Ellyes Skhiri'              );
INSERT INTO Players VALUES (DEFAULT, 15, 'Ghailene Chaalali'            );
INSERT INTO Players VALUES (DEFAULT, 15, 'Anis Ben Slimane'             );
INSERT INTO Players VALUES (DEFAULT, 15, 'Chaïm El Djebali'             );
INSERT INTO Players VALUES (DEFAULT, 15, 'Aïssa Laïdouni'             );
INSERT INTO Players VALUES (DEFAULT, 15, 'Youssef Msakni'             );
INSERT INTO Players VALUES (DEFAULT, 15, 'Wahbi Khazri'               );
INSERT INTO Players VALUES (DEFAULT, 15, 'Taha Yassine Khenissi'          );
INSERT INTO Players VALUES (DEFAULT, 15, 'Seifeddine Jaziri'            );
INSERT INTO Players VALUES (DEFAULT, 15, 'Naïm Sliti'               );
INSERT INTO Players VALUES (DEFAULT, 15, 'Issam Jebali'               );
INSERT INTO Players VALUES (DEFAULT, 15, 'Sayfallah Ltaief'             );

INSERT INTO Players VALUES (DEFAULT, 16, 'Andrew Redmayne'      );
INSERT INTO Players VALUES (DEFAULT, 16, 'Mitchell Langerak'    );
INSERT INTO Players VALUES (DEFAULT, 16, 'Milos Degenek'      );
INSERT INTO Players VALUES (DEFAULT, 16, 'Nathaniel Atkinson'   );
INSERT INTO Players VALUES (DEFAULT, 16, 'Joel King'        );
INSERT INTO Players VALUES (DEFAULT, 16, 'Ryan Strain'        );
INSERT INTO Players VALUES (DEFAULT, 16, 'Thomas Deng'        );
INSERT INTO Players VALUES (DEFAULT, 16, 'Harrison Delbridge'   );
INSERT INTO Players VALUES (DEFAULT, 16, 'Keanu Baccus'       );
INSERT INTO Players VALUES (DEFAULT, 16, 'Denis Genreau'      );
INSERT INTO Players VALUES (DEFAULT, 16, 'Riley McGree'       );
INSERT INTO Players VALUES (DEFAULT, 16, 'Cameron Devlin'     );
INSERT INTO Players VALUES (DEFAULT, 16, 'Tyrese Francois'      );
INSERT INTO Players VALUES (DEFAULT, 16, 'Connor Metcalfe'      );
INSERT INTO Players VALUES (DEFAULT, 16, 'Mathew Leckie'      );
INSERT INTO Players VALUES (DEFAULT, 16, 'Martin Boyle'       );
INSERT INTO Players VALUES (DEFAULT, 16, 'Mitchell Duke'      );
INSERT INTO Players VALUES (DEFAULT, 16, 'Garang Kuol'        );
INSERT INTO Players VALUES (DEFAULT, 16, 'Jason Cummings'     );
INSERT INTO Players VALUES (DEFAULT, 16, 'Marco Tilio'        );

INSERT INTO Players VALUES (DEFAULT, 17, 'Robert Sánchez'     );
INSERT INTO Players VALUES (DEFAULT, 17, 'David Raya'       );
INSERT INTO Players VALUES (DEFAULT, 17, 'Unai Simón'       );
INSERT INTO Players VALUES (DEFAULT, 17, 'Pau Torres'       );
INSERT INTO Players VALUES (DEFAULT, 17, 'Hugo Guillamón'     );
INSERT INTO Players VALUES (DEFAULT, 17, 'José Gayà  25 May '   );
INSERT INTO Players VALUES (DEFAULT, 17, 'Diego Llorente'     );
INSERT INTO Players VALUES (DEFAULT, 17, 'Jordi Alba'       );
INSERT INTO Players VALUES (DEFAULT, 17, 'Dani Carvajal'      );
INSERT INTO Players VALUES (DEFAULT, 17, 'César Azpilicueta'    );
INSERT INTO Players VALUES (DEFAULT, 17, 'Eric García'        );
INSERT INTO Players VALUES (DEFAULT, 17, 'Sergio Busquets'      );
INSERT INTO Players VALUES (DEFAULT, 17, 'Marcos Llorente'      );
INSERT INTO Players VALUES (DEFAULT, 17, 'Koke'           );
INSERT INTO Players VALUES (DEFAULT, 17, 'Gavi'           );
INSERT INTO Players VALUES (DEFAULT, 17, 'Marco Asensio'      );
INSERT INTO Players VALUES (DEFAULT, 17, 'Ferran Torres'      );
INSERT INTO Players VALUES (DEFAULT, 17, 'Rodri'          );
INSERT INTO Players VALUES (DEFAULT, 17, 'Carlos Soler'       );
INSERT INTO Players VALUES (DEFAULT, 17, 'Pedri'          );
INSERT INTO Players VALUES (DEFAULT, 17, 'Pablo Sarabia'      );
INSERT INTO Players VALUES (DEFAULT, 17, 'Nico Williams'      );
INSERT INTO Players VALUES (DEFAULT, 17, 'Borja Iglesias'     );
INSERT INTO Players VALUES (DEFAULT, 17, 'Álvaro Morata'      );
INSERT INTO Players VALUES (DEFAULT, 17, 'Yeremy Pino'        );
 
INSERT INTO Players VALUES (DEFAULT, 18, 'Oliver Baumann'             );
INSERT INTO Players VALUES (DEFAULT, 18, 'Kevin Trapp'                );
INSERT INTO Players VALUES (DEFAULT, 18, 'Marc-André ter Stegen'          );
INSERT INTO Players VALUES (DEFAULT, 18, 'David Raum'               );
INSERT INTO Players VALUES (DEFAULT, 18, 'Matthias Ginter'              );
INSERT INTO Players VALUES (DEFAULT, 18, 'Thilo Kehrer'               );
INSERT INTO Players VALUES (DEFAULT, 18, 'Niklas Süle'                );
INSERT INTO Players VALUES (DEFAULT, 18, 'Benjamin Henrichs'            );
INSERT INTO Players VALUES (DEFAULT, 18, 'Armel Bella-Kotchap'            );
INSERT INTO Players VALUES (DEFAULT, 18, 'Robin Gosens'               );
INSERT INTO Players VALUES (DEFAULT, 18, 'Nico Schlotterbeck'           );
INSERT INTO Players VALUES (DEFAULT, 18, 'Joshua Kimmich'             );
INSERT INTO Players VALUES (DEFAULT, 18, 'Kai Havertz'                );
INSERT INTO Players VALUES (DEFAULT, 18, 'Maximilian Arnold'            );
INSERT INTO Players VALUES (DEFAULT, 18, 'Jamal Musiala'              );
INSERT INTO Players VALUES (DEFAULT, 18, 'Jonas Hofmann'              );
INSERT INTO Players VALUES (DEFAULT, 18, 'İlkay Gündoğan'             );
INSERT INTO Players VALUES (DEFAULT, 18, 'Timo Werner'                );
INSERT INTO Players VALUES (DEFAULT, 18, 'Serge Gnabry'               );
INSERT INTO Players VALUES (DEFAULT, 18, 'Thomas Müller'              );
INSERT INTO Players VALUES (DEFAULT, 18, 'Leroy Sané'               );

INSERT INTO Players VALUES (DEFAULT, 19, 'Eiji Kawashima'   );
INSERT INTO Players VALUES (DEFAULT, 19, 'Daniel Schmidt'   );
INSERT INTO Players VALUES (DEFAULT, 19, 'Kosei Tani'     );
INSERT INTO Players VALUES (DEFAULT, 19, 'Miki Yamane'      );
INSERT INTO Players VALUES (DEFAULT, 19, 'Shogo Taniguchi'    );
INSERT INTO Players VALUES (DEFAULT, 19, 'Ayumu Seko'     );
INSERT INTO Players VALUES (DEFAULT, 19, 'Yuto Nagatomo'    );
INSERT INTO Players VALUES (DEFAULT, 19, 'Hiroki Sakai'     );
INSERT INTO Players VALUES (DEFAULT, 19, 'Yuta Nakayama'    );
INSERT INTO Players VALUES (DEFAULT, 19, 'Maya Yoshida'     );
INSERT INTO Players VALUES (DEFAULT, 19, 'Hiroki Ito'     );
INSERT INTO Players VALUES (DEFAULT, 19, 'Wataru Endo'      );
INSERT INTO Players VALUES (DEFAULT, 19, 'Gaku Shibasaki'   );
INSERT INTO Players VALUES (DEFAULT, 19, 'Genki Haraguchi'    );
INSERT INTO Players VALUES (DEFAULT, 19, 'Takumi Minamino'    );
INSERT INTO Players VALUES (DEFAULT, 19, 'Takefusa Kubo'    );
INSERT INTO Players VALUES (DEFAULT, 19, 'Hidemasa Morita'    );
INSERT INTO Players VALUES (DEFAULT, 19, 'Junya Ito'      );
INSERT INTO Players VALUES (DEFAULT, 19, 'Daichi Kamada'    );
INSERT INTO Players VALUES (DEFAULT, 19, 'Ao Tanaka'      );
INSERT INTO Players VALUES (DEFAULT, 19, 'Kaoru Mitoma'     );
INSERT INTO Players VALUES (DEFAULT, 19, 'Ritsu Dōan'     );
INSERT INTO Players VALUES (DEFAULT, 19, 'Reo Hatate'     );
INSERT INTO Players VALUES (DEFAULT, 19, 'Yuki Soma'      );
INSERT INTO Players VALUES (DEFAULT, 19, 'Kyogo Furuhashi'    );
INSERT INTO Players VALUES (DEFAULT, 19, 'Daizen Maeda'     );
INSERT INTO Players VALUES (DEFAULT, 19, 'Ayase Ueda'     );
INSERT INTO Players VALUES (DEFAULT, 19, 'Shuto Machino'    );

INSERT INTO Players VALUES (DEFAULT, 20, 'Esteban Alvarado'       );
INSERT INTO Players VALUES (DEFAULT, 20, 'Aarón Cruz'         );
INSERT INTO Players VALUES (DEFAULT, 20, 'Patrick Sequeira'       );
INSERT INTO Players VALUES (DEFAULT, 20, 'Juan Pablo Vargas'      );
INSERT INTO Players VALUES (DEFAULT, 20, 'Keysher Fuller'       );
INSERT INTO Players VALUES (DEFAULT, 20, 'Óscar Duarte'         );
INSERT INTO Players VALUES (DEFAULT, 20, 'Bryan Oviedo'         );
INSERT INTO Players VALUES (DEFAULT, 20, 'Francisco Calvo'        );
INSERT INTO Players VALUES (DEFAULT, 20, 'Kendall Waston'       );
INSERT INTO Players VALUES (DEFAULT, 20, 'Carlos Martínez'        );
INSERT INTO Players VALUES (DEFAULT, 20, 'Daniel Chacón'        );
INSERT INTO Players VALUES (DEFAULT, 20, 'Celso Borges'         );
INSERT INTO Players VALUES (DEFAULT, 20, 'Jewison Bennette'       );
INSERT INTO Players VALUES (DEFAULT, 20, 'Bryan Ruiz'         );
INSERT INTO Players VALUES (DEFAULT, 20, 'Gerson Torres'        );
INSERT INTO Players VALUES (DEFAULT, 20, 'Orlando Galo'         );
INSERT INTO Players VALUES (DEFAULT, 20, 'Aarón Suárez'         );
INSERT INTO Players VALUES (DEFAULT, 20, 'Roan Wilson'          );
INSERT INTO Players VALUES (DEFAULT, 20, 'Brandon Aguilera'       );
INSERT INTO Players VALUES (DEFAULT, 20, 'Carlos Mora'          );
INSERT INTO Players VALUES (DEFAULT, 20, 'Douglas López'        );
INSERT INTO Players VALUES (DEFAULT, 20, 'Anthony Hernández'      );
INSERT INTO Players VALUES (DEFAULT, 20, 'Álvaro Zamora'        );
INSERT INTO Players VALUES (DEFAULT, 20, 'Anthony Contreras'      );
INSERT INTO Players VALUES (DEFAULT, 20, 'Johan Venegas'        );
INSERT INTO Players VALUES (DEFAULT, 20, 'Joel Campbell'        );

INSERT INTO Players VALUES (DEFAULT, 21, 'Thibaut Courtois'             );
INSERT INTO Players VALUES (DEFAULT, 21, 'Simon Mignolet'             );
INSERT INTO Players VALUES (DEFAULT, 21, 'Koen Casteels'              );
INSERT INTO Players VALUES (DEFAULT, 21, 'Matz Sels'                );
INSERT INTO Players VALUES (DEFAULT, 21, 'Toby Alderweireld'            );
INSERT INTO Players VALUES (DEFAULT, 21, 'Arthur Theate'              );
INSERT INTO Players VALUES (DEFAULT, 21, 'Zeno Debast'                );
INSERT INTO Players VALUES (DEFAULT, 21, 'Jan Vertonghen'             );
INSERT INTO Players VALUES (DEFAULT, 21, 'Thomas Meunier'             );
INSERT INTO Players VALUES (DEFAULT, 21, 'Brandon Mechele'              );
INSERT INTO Players VALUES (DEFAULT, 21, 'Dedryck Boyata'             );
INSERT INTO Players VALUES (DEFAULT, 21, 'Jason Denayer'              );
INSERT INTO Players VALUES (DEFAULT, 21, 'Wout Faes'                );
INSERT INTO Players VALUES (DEFAULT, 21, 'Axel Witsel'                );
INSERT INTO Players VALUES (DEFAULT, 21, 'Kevin De Bruyne'              );
INSERT INTO Players VALUES (DEFAULT, 21, 'Youri Tielemans'              );
INSERT INTO Players VALUES (DEFAULT, 21, 'Yannick Carrasco'             );
INSERT INTO Players VALUES (DEFAULT, 21, 'Charles De Ketelaere'           );
INSERT INTO Players VALUES (DEFAULT, 21, 'Leandro Trossard'             );
INSERT INTO Players VALUES (DEFAULT, 21, 'Amadou Onana'               );
INSERT INTO Players VALUES (DEFAULT, 21, 'Leander Dendoncker'           );
INSERT INTO Players VALUES (DEFAULT, 21, 'Hans Vanaken'               );
INSERT INTO Players VALUES (DEFAULT, 21, 'Timothy Castagne'             );
INSERT INTO Players VALUES (DEFAULT, 21, 'Alexis Saelemaekers'            );
INSERT INTO Players VALUES (DEFAULT, 21, 'Loïs Openda'                );
INSERT INTO Players VALUES (DEFAULT, 21, 'Eden Hazard'                );
INSERT INTO Players VALUES (DEFAULT, 21, 'Dries Mertens'              );
INSERT INTO Players VALUES (DEFAULT, 21, 'Michy Batshuayi'              );
INSERT INTO Players VALUES (DEFAULT, 21, 'Thorgan Hazard'             );
INSERT INTO Players VALUES (DEFAULT, 21, 'Dodi Lukebakio'             );

INSERT INTO Players VALUES (DEFAULT, 22, 'Maxime Crépeau'             );
INSERT INTO Players VALUES (DEFAULT, 22, 'Dayne St. Clair'              );
INSERT INTO Players VALUES (DEFAULT, 22, 'Milan Borjan'               );
INSERT INTO Players VALUES (DEFAULT, 22, 'Alistair Johnston'            );
INSERT INTO Players VALUES (DEFAULT, 22, 'Sam Adekugbe'               );
INSERT INTO Players VALUES (DEFAULT, 22, 'Kamal Miller'               );
INSERT INTO Players VALUES (DEFAULT, 22, 'Steven Vitória'             );
INSERT INTO Players VALUES (DEFAULT, 22, 'Derek Cornelius'              );
INSERT INTO Players VALUES (DEFAULT, 22, 'Alphonso Davies'              );
INSERT INTO Players VALUES (DEFAULT, 22, 'Richie Laryea'              );
INSERT INTO Players VALUES (DEFAULT, 22, 'Scott Kennedy'              );
INSERT INTO Players VALUES (DEFAULT, 22, 'Joel Waterman'              );
INSERT INTO Players VALUES (DEFAULT, 22, 'Samuel Piette'              );
INSERT INTO Players VALUES (DEFAULT, 22, 'Stephen Eustáquio'            );
INSERT INTO Players VALUES (DEFAULT, 22, 'Ismaël Koné'                );
INSERT INTO Players VALUES (DEFAULT, 22, 'Mark-Anthony Kaye'            );
INSERT INTO Players VALUES (DEFAULT, 22, 'Lucas Cavallini'              );
INSERT INTO Players VALUES (DEFAULT, 22, 'Junior Hoilett'             );
INSERT INTO Players VALUES (DEFAULT, 22, 'Tajon Buchanan'             );
INSERT INTO Players VALUES (DEFAULT, 22, 'Iké Ugbo'                 );
INSERT INTO Players VALUES (DEFAULT, 22, 'Charles-Andreas Brym'           );
INSERT INTO Players VALUES (DEFAULT, 22, 'Cyle Larin'               );
INSERT INTO Players VALUES (DEFAULT, 22, 'Jonathan David'             );
INSERT INTO Players VALUES (DEFAULT, 22, 'Liam Millar'                );
INSERT INTO Players VALUES (DEFAULT, 22, 'Theo Corbeanu'              );
INSERT INTO Players VALUES (DEFAULT, 22, 'Luca Koleosho'              );

INSERT INTO Players VALUES (DEFAULT, 23, 'Yassine Bounou'             );
INSERT INTO Players VALUES (DEFAULT, 23, 'Munir Mohamedi'             );
INSERT INTO Players VALUES (DEFAULT, 23, 'Ahmed Reda Tagnaouti'           );
INSERT INTO Players VALUES (DEFAULT, 23, 'Anas Zniti'               );
INSERT INTO Players VALUES (DEFAULT, 23, 'Achraf Hakimi'              );
INSERT INTO Players VALUES (DEFAULT, 23, 'Noussair Mazraoui'            ); 
INSERT INTO Players VALUES (DEFAULT, 23, 'Jawad El Yamiq'             );
INSERT INTO Players VALUES (DEFAULT, 23, 'Romain Saïss'               );
INSERT INTO Players VALUES (DEFAULT, 23, 'Achraf Dari'                );
INSERT INTO Players VALUES (DEFAULT, 23, 'Samy Mmaee'               );
INSERT INTO Players VALUES (DEFAULT, 23, 'Yahia Attiyat Allah'            ); 
INSERT INTO Players VALUES (DEFAULT, 23, 'Badr Benoun'                );
INSERT INTO Players VALUES (DEFAULT, 23, 'Fahd Moufi'               );
INSERT INTO Players VALUES (DEFAULT, 23, 'Sofyan Amrabat'             );
INSERT INTO Players VALUES (DEFAULT, 23, 'Azzedine Ounahi'              );
INSERT INTO Players VALUES (DEFAULT, 23, 'Younès Belhanda'              );
INSERT INTO Players VALUES (DEFAULT, 23, 'Abdelhamid Sabiri'            );
INSERT INTO Players VALUES (DEFAULT, 23, 'Ilias Chair'                );
INSERT INTO Players VALUES (DEFAULT, 23, 'Selim Amallah'              );
INSERT INTO Players VALUES (DEFAULT, 23, 'Amine Harit'                );
INSERT INTO Players VALUES (DEFAULT, 23, 'Yahya Jabrane'              );
INSERT INTO Players VALUES (DEFAULT, 23, 'Hakim Ziyech'               );
INSERT INTO Players VALUES (DEFAULT, 23, 'Munir El Haddadi'             );
INSERT INTO Players VALUES (DEFAULT, 23, 'Zakaria Aboukhlal'            );
INSERT INTO Players VALUES (DEFAULT, 23, 'Abde Ezzalzouli'              );
INSERT INTO Players VALUES (DEFAULT, 23, 'Sofiane Boufal'             );
INSERT INTO Players VALUES (DEFAULT, 23, 'Youssef En-Nesyri'            );
INSERT INTO Players VALUES (DEFAULT, 23, 'Walid Cheddira'             );
INSERT INTO Players VALUES (DEFAULT, 23, 'Ryan Mmaee'               );
INSERT INTO Players VALUES (DEFAULT, 23, 'Ayoub El Kaabi'             );
INSERT INTO Players VALUES (DEFAULT, 23, 'Soufiane Rahimi'              );
 
INSERT INTO Players VALUES (DEFAULT, 24, 'Dominik Livaković'          );
INSERT INTO Players VALUES (DEFAULT, 24, 'Lovre Kalinić'            );
INSERT INTO Players VALUES (DEFAULT, 24, 'Ivica Ivušić'             );
INSERT INTO Players VALUES (DEFAULT, 24, 'Josip Stanišić'           );
INSERT INTO Players VALUES (DEFAULT, 24, 'Borna Barišić'            );
INSERT INTO Players VALUES (DEFAULT, 24, 'Martin Erlić'             );
INSERT INTO Players VALUES (DEFAULT, 24, 'Dejan Lovren'             );
INSERT INTO Players VALUES (DEFAULT, 24, 'Borna Sosa'             );
INSERT INTO Players VALUES (DEFAULT, 24, 'Joško Gvardiol'           );
INSERT INTO Players VALUES (DEFAULT, 24, 'Domagoj Vida'             );
INSERT INTO Players VALUES (DEFAULT, 24, 'Josip Juranović'            );
INSERT INTO Players VALUES (DEFAULT, 24, 'Josip Šutalo'             );
INSERT INTO Players VALUES (DEFAULT, 24, 'Lovro Majer'              );
INSERT INTO Players VALUES (DEFAULT, 24, 'Mateo Kovačić'            );
INSERT INTO Players VALUES (DEFAULT, 24, 'Luka Modrić'              );
INSERT INTO Players VALUES (DEFAULT, 24, 'Marcelo Brozović'           );
INSERT INTO Players VALUES (DEFAULT, 24, 'Nikola Vlašić'            );
INSERT INTO Players VALUES (DEFAULT, 24, 'Mario Pašalić'            );
INSERT INTO Players VALUES (DEFAULT, 24, 'Luka Sučić'             );
INSERT INTO Players VALUES (DEFAULT, 24, 'Ivan Perišić'             );
INSERT INTO Players VALUES (DEFAULT, 24, 'Andrej Kramarić'            );
INSERT INTO Players VALUES (DEFAULT, 24, 'Marko Livaja'             );
INSERT INTO Players VALUES (DEFAULT, 24, 'Bruno Petković'           );
INSERT INTO Players VALUES (DEFAULT, 24, 'Ante Budimir'             );
INSERT INTO Players VALUES (DEFAULT, 24, 'Mislav Oršić'             );
 
INSERT INTO Players VALUES (DEFAULT, 25, 'Alisson'                );
INSERT INTO Players VALUES (DEFAULT, 25, 'Weverton'               );
INSERT INTO Players VALUES (DEFAULT, 25, 'Ederson'                );
INSERT INTO Players VALUES (DEFAULT, 25, 'Danilo'               );
INSERT INTO Players VALUES (DEFAULT, 25, 'Thiago Silva'             );
INSERT INTO Players VALUES (DEFAULT, 25, 'Marquinhos'             );
INSERT INTO Players VALUES (DEFAULT, 25, 'Alex Telles'              );
INSERT INTO Players VALUES (DEFAULT, 25, 'Roger Ibañez'             );
INSERT INTO Players VALUES (DEFAULT, 25, 'Éder Militão'             );
INSERT INTO Players VALUES (DEFAULT, 25, 'Renan Lodi'             );
INSERT INTO Players VALUES (DEFAULT, 25, 'Bremer'               );
INSERT INTO Players VALUES (DEFAULT, 25, 'Casemiro'               );
INSERT INTO Players VALUES (DEFAULT, 25, 'Lucas Paquetá'            );
INSERT INTO Players VALUES (DEFAULT, 25, 'Fred'                 );
INSERT INTO Players VALUES (DEFAULT, 25, 'Éverton Ribeiro'            );
INSERT INTO Players VALUES (DEFAULT, 25, 'Fabinho'                );
INSERT INTO Players VALUES (DEFAULT, 25, 'Bruno Guimarães'            );
INSERT INTO Players VALUES (DEFAULT, 25, 'Richarlison'              );
INSERT INTO Players VALUES (DEFAULT, 25, 'Neymar'               );
INSERT INTO Players VALUES (DEFAULT, 25, 'Antony'               );
INSERT INTO Players VALUES (DEFAULT, 25, 'Raphinha'               );
INSERT INTO Players VALUES (DEFAULT, 25, 'Vinícius Júnior'            );
INSERT INTO Players VALUES (DEFAULT, 25, 'Matheus Cunha'            );
INSERT INTO Players VALUES (DEFAULT, 25, 'Roberto Firmino'            );
INSERT INTO Players VALUES (DEFAULT, 25, 'Pedro'                );
INSERT INTO Players VALUES (DEFAULT, 25, 'Rodrygo'                );
 
INSERT INTO Players VALUES (DEFAULT, 26, 'Marko Dmitrović'              );
INSERT INTO Players VALUES (DEFAULT, 26, 'Vanja Milinković-Savić'         ); 
INSERT INTO Players VALUES (DEFAULT, 26, 'Marko Ilić'               );
INSERT INTO Players VALUES (DEFAULT, 26, 'Stefan Mitrović'              );
INSERT INTO Players VALUES (DEFAULT, 26, 'Strahinja Pavlović'           );
INSERT INTO Players VALUES (DEFAULT, 26, 'Miloš Veljković'              );
INSERT INTO Players VALUES (DEFAULT, 26, 'Filip Mladenović'             );
INSERT INTO Players VALUES (DEFAULT, 26, 'Aleksa Terzić'              );
INSERT INTO Players VALUES (DEFAULT, 26, 'Srđan Babić'                );
INSERT INTO Players VALUES (DEFAULT, 26, 'Erhan Mašović'              );
INSERT INTO Players VALUES (DEFAULT, 26, 'Strahinja Eraković'           );
INSERT INTO Players VALUES (DEFAULT, 26, 'Dušan Tadić'                );
INSERT INTO Players VALUES (DEFAULT, 26, 'Filip Kostić'               );
INSERT INTO Players VALUES (DEFAULT, 26, 'Nemanja Maksimović'           );
INSERT INTO Players VALUES (DEFAULT, 26, 'Nemanja Radonjić'             );
INSERT INTO Players VALUES (DEFAULT, 26, 'Filip Đuričić'              );
INSERT INTO Players VALUES (DEFAULT, 26, 'Saša Lukić'               );
INSERT INTO Players VALUES (DEFAULT, 26, 'Andrija Živković'             );
INSERT INTO Players VALUES (DEFAULT, 26, 'Darko Lazović'              );
INSERT INTO Players VALUES (DEFAULT, 26, 'Ivan Ilić'                );
INSERT INTO Players VALUES (DEFAULT, 26, 'Stefan Mitrović'              );
INSERT INTO Players VALUES (DEFAULT, 26, 'Aleksandar Mitrović'            ); 
INSERT INTO Players VALUES (DEFAULT, 26, 'Luka Jović'               );
INSERT INTO Players VALUES (DEFAULT, 26, 'Dušan Vlahović'             );
 
INSERT INTO Players VALUES (DEFAULT, 27, 'Yann Sommer'        );
INSERT INTO Players VALUES (DEFAULT, 27, 'Yvon Mvogo'     );
INSERT INTO Players VALUES (DEFAULT, 27, 'David von Ballmoos' );
INSERT INTO Players VALUES (DEFAULT, 27, 'Ricardo Rodriguez'  );
INSERT INTO Players VALUES (DEFAULT, 27, 'Fabian Schär'       );
INSERT INTO Players VALUES (DEFAULT, 27, 'Manuel Akanji'    );
INSERT INTO Players VALUES (DEFAULT, 27, 'Nico Elvedi'        );
INSERT INTO Players VALUES (DEFAULT, 27, 'Silvan Widmer'    );
INSERT INTO Players VALUES (DEFAULT, 27, 'Kevin Mbabu'        );
INSERT INTO Players VALUES (DEFAULT, 27, 'Eray Cömert'        );
INSERT INTO Players VALUES (DEFAULT, 27, 'Xherdan Shaqiri'      );
INSERT INTO Players VALUES (DEFAULT, 27, 'Granit Xhaka'       );
INSERT INTO Players VALUES (DEFAULT, 27, 'Remo Freuler'       );
INSERT INTO Players VALUES (DEFAULT, 27, 'Denis Zakaria'    );
INSERT INTO Players VALUES (DEFAULT, 27, 'Djibril Sow'        );
INSERT INTO Players VALUES (DEFAULT, 27, 'Renato Steffen'   );
INSERT INTO Players VALUES (DEFAULT, 27, 'Fabian Frei'        );
INSERT INTO Players VALUES (DEFAULT, 27, 'Michel Aebischer'     );
INSERT INTO Players VALUES (DEFAULT, 27, 'Ardon Jashari'    );
INSERT INTO Players VALUES (DEFAULT, 27, 'Haris Seferovic'      );
INSERT INTO Players VALUES (DEFAULT, 27, 'Breel Embolo'       );
INSERT INTO Players VALUES (DEFAULT, 27, 'Ruben Vargas'       );
INSERT INTO Players VALUES (DEFAULT, 27, 'Cedric Itten'       );
INSERT INTO Players VALUES (DEFAULT, 27, 'Dan Ndoye'        );
INSERT INTO Players VALUES (DEFAULT, 27, 'Zeki Amdouni'       );
 
INSERT INTO Players VALUES (DEFAULT, 28, 'Simon Ngapandouetnbu'       ); 
INSERT INTO Players VALUES (DEFAULT, 28, 'Devis Epassy'           );
INSERT INTO Players VALUES (DEFAULT, 28, 'André Onana'          );
INSERT INTO Players VALUES (DEFAULT, 28, 'Darlin Yongwa'        );
INSERT INTO Players VALUES (DEFAULT, 28, 'Nicolas Nkoulou'        );
INSERT INTO Players VALUES (DEFAULT, 28, 'Christopher Wooh'         );
INSERT INTO Players VALUES (DEFAULT, 28, 'Oumar Gonzalez'       );
INSERT INTO Players VALUES (DEFAULT, 28, 'Nouhou Tolo'          );
INSERT INTO Players VALUES (DEFAULT, 28, 'Olivier Mbaizo'       );
INSERT INTO Players VALUES (DEFAULT, 28, 'Collins Fai'          );
INSERT INTO Players VALUES (DEFAULT, 28, 'Jean-Charles Castelletto'   ); 
INSERT INTO Players VALUES (DEFAULT, 28, 'Enzo Ebosse'          );
INSERT INTO Players VALUES (DEFAULT, 28, 'Olivier Ntcham'       );
INSERT INTO Players VALUES (DEFAULT, 28, 'Georges Mandjeck'         );
INSERT INTO Players VALUES (DEFAULT, 28, 'Pierre Kunde'           );
INSERT INTO Players VALUES (DEFAULT, 28, 'Martin Hongla'        );
INSERT INTO Players VALUES (DEFAULT, 28, 'Samuel Gouet'           );
INSERT INTO Players VALUES (DEFAULT, 28, 'Gaël Ondoua'          );
INSERT INTO Players VALUES (DEFAULT, 28, 'Jean Onana'         );
INSERT INTO Players VALUES (DEFAULT, 28, 'Moumi Ngamaleu'       );
INSERT INTO Players VALUES (DEFAULT, 28, 'Georges-Kévin Nkoudou'    ); 
INSERT INTO Players VALUES (DEFAULT, 28, 'Léandre Tawamba'        );
INSERT INTO Players VALUES (DEFAULT, 28, 'Vincent Aboubakar'      );
INSERT INTO Players VALUES (DEFAULT, 28, 'Karl Toko Ekambi'         );
INSERT INTO Players VALUES (DEFAULT, 28, 'Jean-Pierre Nsame'      );
INSERT INTO Players VALUES (DEFAULT, 28, 'Bryan Mbeumo'           );
 
INSERT INTO Players VALUES (DEFAULT, 29, 'Rui Patrício'         );
INSERT INTO Players VALUES (DEFAULT, 29, 'José Sá'          );
INSERT INTO Players VALUES (DEFAULT, 29, 'Diogo Costa'        );
INSERT INTO Players VALUES (DEFAULT, 29, 'Diogo Dalot'        );
INSERT INTO Players VALUES (DEFAULT, 29, 'Tiago Djaló'        );
INSERT INTO Players VALUES (DEFAULT, 29, 'Rúben Dias'       );
INSERT INTO Players VALUES (DEFAULT, 29, 'Nuno Mendes'        );
INSERT INTO Players VALUES (DEFAULT, 29, 'Danilo Pereira'     );
INSERT INTO Players VALUES (DEFAULT, 29, 'Mário Rui'        );
INSERT INTO Players VALUES (DEFAULT, 29, 'João Cancelo'         );
INSERT INTO Players VALUES (DEFAULT, 29, 'João Palhinha'      );
INSERT INTO Players VALUES (DEFAULT, 29, 'Bruno Fernandes'      );
INSERT INTO Players VALUES (DEFAULT, 29, 'Bernardo Silva'     );
INSERT INTO Players VALUES (DEFAULT, 29, 'Matheus Nunes'      );
INSERT INTO Players VALUES (DEFAULT, 29, 'William Carvalho'       );
INSERT INTO Players VALUES (DEFAULT, 29, 'Vitinha'          );
INSERT INTO Players VALUES (DEFAULT, 29, 'João Mário'       );
INSERT INTO Players VALUES (DEFAULT, 29, 'Rúben Neves'        );
INSERT INTO Players VALUES (DEFAULT, 29, 'Cristiano Ronaldo'    );
INSERT INTO Players VALUES (DEFAULT, 29, 'Ricardo Horta'      );
INSERT INTO Players VALUES (DEFAULT, 29, 'Rafael Leão'        );
INSERT INTO Players VALUES (DEFAULT, 29, 'Diogo Jota'       );
INSERT INTO Players VALUES (DEFAULT, 29, 'João Félix'       );
INSERT INTO Players VALUES (DEFAULT, 29, 'Pedro Neto'       );
INSERT INTO Players VALUES (DEFAULT, 29, 'Gonçalo Ramos'      );
 
INSERT INTO Players VALUES (DEFAULT, 30, 'Richard Ofori'          );
INSERT INTO Players VALUES (DEFAULT, 30, 'Abdul Manaf Nurudeen'       ); 
INSERT INTO Players VALUES (DEFAULT, 30, 'Joe Wollacott'          );
INSERT INTO Players VALUES (DEFAULT, 30, 'Tariq Lamptey'          );
INSERT INTO Players VALUES (DEFAULT, 30, 'Denis Odoi'           );
INSERT INTO Players VALUES (DEFAULT, 30, 'Mohammed Salisu'          );
INSERT INTO Players VALUES (DEFAULT, 30, 'Gideon Mensah'          );
INSERT INTO Players VALUES (DEFAULT, 30, 'Joseph Aidoo'           );
INSERT INTO Players VALUES (DEFAULT, 30, 'Abdul Rahman Baba'        );
INSERT INTO Players VALUES (DEFAULT, 30, 'Daniel Amartey'         );
INSERT INTO Players VALUES (DEFAULT, 30, 'Alexander Djiku'          );
INSERT INTO Players VALUES (DEFAULT, 30, 'Alidu Seidu'            );
INSERT INTO Players VALUES (DEFAULT, 30, 'Stephan Ambrosius'        );
INSERT INTO Players VALUES (DEFAULT, 30, 'Thomas Partey'          );
INSERT INTO Players VALUES (DEFAULT, 30, 'Elisha Owusu'           );
INSERT INTO Players VALUES (DEFAULT, 30, 'Daniel-Kofi Kyereh'       );
INSERT INTO Players VALUES (DEFAULT, 30, 'André Ayew'           );
INSERT INTO Players VALUES (DEFAULT, 30, 'Mohammed Kudus'         );
INSERT INTO Players VALUES (DEFAULT, 30, 'Iddrisu Baba'           );
INSERT INTO Players VALUES (DEFAULT, 30, 'Abdul Fatawu Issahaku'      ); 
INSERT INTO Players VALUES (DEFAULT, 30, 'Jordan Ayew'            );
INSERT INTO Players VALUES (DEFAULT, 30, 'Osman Bukari'           );
INSERT INTO Players VALUES (DEFAULT, 30, 'Felix Afena-Gyan'         );
INSERT INTO Players VALUES (DEFAULT, 30, 'Iñaki Williams'         );
INSERT INTO Players VALUES (DEFAULT, 30, 'Kamaldeen Sulemana'       );
INSERT INTO Players VALUES (DEFAULT, 30, 'Antoine Semenyo'          );
INSERT INTO Players VALUES (DEFAULT, 30, 'Daniel Afriyie'         );
INSERT INTO Players VALUES (DEFAULT, 30, 'Benjamin Tetteh'          );
INSERT INTO Players VALUES (DEFAULT, 30, 'Ransford-Yeboah Königsdörffer'  ); 
 
INSERT INTO Players VALUES (DEFAULT, 31, 'Fernando Muslera'          );
INSERT INTO Players VALUES (DEFAULT, 31, 'Sebastián Sosa'        );
INSERT INTO Players VALUES (DEFAULT, 31, 'Sergio Rochet'         );
INSERT INTO Players VALUES (DEFAULT, 31, 'Agustín Rogel'         );
INSERT INTO Players VALUES (DEFAULT, 31, 'Sebastián Cáceres'       );
INSERT INTO Players VALUES (DEFAULT, 31, 'Damián Suárez'         );
INSERT INTO Players VALUES (DEFAULT, 31, 'Mathías Olivera'           );
INSERT INTO Players VALUES (DEFAULT, 31, 'Matías Viña'             );
INSERT INTO Players VALUES (DEFAULT, 31, 'Guillermo Varela'          );
INSERT INTO Players VALUES (DEFAULT, 31, 'Martín Cáceres'        );
INSERT INTO Players VALUES (DEFAULT, 31, 'Leandro Cabrera'           );
INSERT INTO Players VALUES (DEFAULT, 31, 'Matías Vecino'         );
INSERT INTO Players VALUES (DEFAULT, 31, 'Rodrigo Bentancur'       );
INSERT INTO Players VALUES (DEFAULT, 31, 'Nicolás de la Cruz'      );
INSERT INTO Players VALUES (DEFAULT, 31, 'Giorgian de Arrascaeta'    ); 
INSERT INTO Players VALUES (DEFAULT, 31, 'Lucas Torreira'        );
INSERT INTO Players VALUES (DEFAULT, 31, 'Federico Valverde'       );
INSERT INTO Players VALUES (DEFAULT, 31, 'Manuel Ugarte'         );
INSERT INTO Players VALUES (DEFAULT, 31, 'Facundo Pellistri'       );
INSERT INTO Players VALUES (DEFAULT, 31, 'Luis Suárez'             );
INSERT INTO Players VALUES (DEFAULT, 31, 'Darwin Núñez'            );
INSERT INTO Players VALUES (DEFAULT, 31, 'Agustín Canobbio'          );
INSERT INTO Players VALUES (DEFAULT, 31, 'Martín Satriano'           );
INSERT INTO Players VALUES (DEFAULT, 31, 'Diego Rossi'             );
INSERT INTO Players VALUES (DEFAULT, 31, 'Brian Ocampo'            );
 
INSERT INTO Players VALUES (DEFAULT, 32, 'Kim Seung-gyu'    );
INSERT INTO Players VALUES (DEFAULT, 32, 'Song Bum-keun'    );
INSERT INTO Players VALUES (DEFAULT, 32, 'Kim Dong-jun'     );
INSERT INTO Players VALUES (DEFAULT, 32, 'Kim Tae-hwan'     );
INSERT INTO Players VALUES (DEFAULT, 32, 'Kim Jin-su'     );
INSERT INTO Players VALUES (DEFAULT, 32, 'Kim Min-jae'      );
INSERT INTO Players VALUES (DEFAULT, 32, 'Hong Chul'      );
INSERT INTO Players VALUES (DEFAULT, 32, 'Cho Yu-min'     );
INSERT INTO Players VALUES (DEFAULT, 32, 'Kim Young-gwon'   );
INSERT INTO Players VALUES (DEFAULT, 32, 'Kwon Kyung-won'   );
INSERT INTO Players VALUES (DEFAULT, 32, 'Kim Moon-hwan'    );
INSERT INTO Players VALUES (DEFAULT, 32, 'Yoon Jong-gyu'    );
INSERT INTO Players VALUES (DEFAULT, 32, 'Jung Woo-young'   );
INSERT INTO Players VALUES (DEFAULT, 32, 'Hwang In-beom'    );
INSERT INTO Players VALUES (DEFAULT, 32, 'Son Heung-min'    );
INSERT INTO Players VALUES (DEFAULT, 32, 'Paik Seung-ho'    );
INSERT INTO Players VALUES (DEFAULT, 32, 'Lee Jae-sung'     );
INSERT INTO Players VALUES (DEFAULT, 32, 'Hwang Hee-chan'   );
INSERT INTO Players VALUES (DEFAULT, 32, 'Son Jun-ho'     );
INSERT INTO Players VALUES (DEFAULT, 32, 'Na Sang-ho'     );
INSERT INTO Players VALUES (DEFAULT, 32, 'Yang Hyun-jun'    );
INSERT INTO Players VALUES (DEFAULT, 32, 'Kwon Chang-hoon'    );
INSERT INTO Players VALUES (DEFAULT, 32, 'Jeong Woo-yeong'    );
INSERT INTO Players VALUES (DEFAULT, 32, 'Lee Kang-in'      );
INSERT INTO Players VALUES (DEFAULT, 32, 'Cho Young-wook'   );
INSERT INTO Players VALUES (DEFAULT, 32, 'Hwang Ui-jo'      );



INSERT INTO Match VALUES (DEFAULT, 1, 2, TO_DATE('20/11/2022 19:00:00', 'dd/mm/yyyy hh24:mi:ss'), NULL, NULL);
INSERT INTO Match VALUES (DEFAULT, 3, 4, TO_DATE('21/11/2022 19:00:00', 'dd/mm/yyyy hh24:mi:ss'), NULL, NULL);
INSERT INTO Match VALUES (DEFAULT, 1, 3, TO_DATE('25/11/2022 16:00:00', 'dd/mm/yyyy hh24:mi:ss'), NULL, NULL);
INSERT INTO Match VALUES (DEFAULT, 4, 2, TO_DATE('25/11/2022 19:00:00', 'dd/mm/yyyy hh24:mi:ss'), NULL, NULL);
INSERT INTO Match VALUES (DEFAULT, 2, 3, TO_DATE('29/11/2022 18:00:00', 'dd/mm/yyyy hh24:mi:ss'), NULL, NULL);
INSERT INTO Match VALUES (DEFAULT, 4, 1, TO_DATE('29/11/2022 18:00:00', 'dd/mm/yyyy hh24:mi:ss'), NULL, NULL);

INSERT INTO Match VALUES (DEFAULT, 5, 6, TO_DATE('21/11/2022 16:00:00', 'dd/mm/yyyy hh24:mi:ss'), NULL, NULL);
INSERT INTO Match VALUES (DEFAULT, 7, 8, TO_DATE('21/11/2022 22:00:00', 'dd/mm/yyyy hh24:mi:ss'), NULL, NULL);
INSERT INTO Match VALUES (DEFAULT, 8, 6, TO_DATE('25/11/2022 13:00:00', 'dd/mm/yyyy hh24:mi:ss'), NULL, NULL);
INSERT INTO Match VALUES (DEFAULT, 5, 7, TO_DATE('25/11/2022 22:00:00', 'dd/mm/yyyy hh24:mi:ss'), NULL, NULL);
INSERT INTO Match VALUES (DEFAULT, 8, 5, TO_DATE('29/11/2022 22:00:00', 'dd/mm/yyyy hh24:mi:ss'), NULL, NULL);
INSERT INTO Match VALUES (DEFAULT, 6, 7, TO_DATE('29/11/2022 22:00:00', 'dd/mm/yyyy hh24:mi:ss'), NULL, NULL);

INSERT INTO Match VALUES (DEFAULT, 9, 10, TO_DATE('22/11/2022 13:00:00', 'dd/mm/yyyy hh24:mi:ss'), NULL, NULL  );
INSERT INTO Match VALUES (DEFAULT, 11, 12, TO_DATE('22/11/2022 19:00:00', 'dd/mm/yyyy hh24:mi:ss'), NULL, NULL );
INSERT INTO Match VALUES (DEFAULT, 12, 10, TO_DATE('26/11/2022 16:00:00', 'dd/mm/yyyy hh24:mi:ss'), NULL, NULL );
INSERT INTO Match VALUES (DEFAULT, 9, 11, TO_DATE('26/11/2022 22:00:00', 'dd/mm/yyyy hh24:mi:ss'), NULL, NULL  );
INSERT INTO Match VALUES (DEFAULT, 12, 9, TO_DATE('30/11/2022 22:00:00', 'dd/mm/yyyy hh24:mi:ss'), NULL, NULL  );
INSERT INTO Match VALUES (DEFAULT, 10, 11, TO_DATE('30/11/2022 22:00:00', 'dd/mm/yyyy hh24:mi:ss'), NULL, NULL );

INSERT INTO Match VALUES (DEFAULT, 14, 15, TO_DATE('22/11/2022 16:00:00', 'dd/mm/yyyy hh24:mi:ss'), NULL, NULL);
INSERT INTO Match VALUES (DEFAULT, 13, 16, TO_DATE('22/11/2022 22:00:00', 'dd/mm/yyyy hh24:mi:ss'), NULL, NULL);
INSERT INTO Match VALUES (DEFAULT, 15, 16, TO_DATE('26/11/2022 13:00:00', 'dd/mm/yyyy hh24:mi:ss'), NULL, NULL);
INSERT INTO Match VALUES (DEFAULT, 13, 14, TO_DATE('26/11/2022 18:00:00', 'dd/mm/yyyy hh24:mi:ss'), NULL, NULL);
INSERT INTO Match VALUES (DEFAULT, 16, 14, TO_DATE('30/11/2022 18:00:00', 'dd/mm/yyyy hh24:mi:ss'), NULL, NULL);
INSERT INTO Match VALUES (DEFAULT, 14, 13, TO_DATE('30/11/2022 18:00:00', 'dd/mm/yyyy hh24:mi:ss'), NULL, NULL);

INSERT INTO Match VALUES (DEFAULT, 18, 19, TO_DATE('23/11/2022 16:00:00', 'dd/mm/yyyy hh24:mi:ss'), NULL, NULL);
INSERT INTO Match VALUES (DEFAULT, 17, 20, TO_DATE('23/11/2022 19:00:00', 'dd/mm/yyyy hh24:mi:ss'), NULL, NULL);
INSERT INTO Match VALUES (DEFAULT, 19, 20, TO_DATE('27/11/2022 13:00:00', 'dd/mm/yyyy hh24:mi:ss'), NULL, NULL);
INSERT INTO Match VALUES (DEFAULT, 17, 18, TO_DATE('27/11/2022 22:00:00', 'dd/mm/yyyy hh24:mi:ss'), NULL, NULL);
INSERT INTO Match VALUES (DEFAULT, 19, 17, TO_DATE('01/12/2022 22:00:00', 'dd/mm/yyyy hh24:mi:ss'), NULL, NULL);
INSERT INTO Match VALUES (DEFAULT, 20, 18, TO_DATE('01/12/2022 22:00:00', 'dd/mm/yyyy hh24:mi:ss'), NULL, NULL);

INSERT INTO Match VALUES (DEFAULT, 23, 24, TO_DATE('23/11/2022 13:00:00', 'dd/mm/yyyy hh24:mi:ss'), NULL, NULL);
INSERT INTO Match VALUES (DEFAULT, 21, 22, TO_DATE('23/11/2022 22:00:00', 'dd/mm/yyyy hh24:mi:ss'), NULL, NULL);
INSERT INTO Match VALUES (DEFAULT, 21, 23, TO_DATE('27/11/2022 16:00:00', 'dd/mm/yyyy hh24:mi:ss'), NULL, NULL);
INSERT INTO Match VALUES (DEFAULT, 24, 22, TO_DATE('27/11/2022 19:00:00', 'dd/mm/yyyy hh24:mi:ss'), NULL, NULL);
INSERT INTO Match VALUES (DEFAULT, 24, 21, TO_DATE('01/12/2022 18:00:00', 'dd/mm/yyyy hh24:mi:ss'), NULL, NULL);
INSERT INTO Match VALUES (DEFAULT, 22, 23, TO_DATE('01/12/2022 18:00:00', 'dd/mm/yyyy hh24:mi:ss'), NULL, NULL);

INSERT INTO Match VALUES (DEFAULT, 27, 28, TO_DATE('24/11/2022 13:00:00', 'dd/mm/yyyy hh24:mi:ss'), NULL, NULL);
INSERT INTO Match VALUES (DEFAULT, 25, 26, TO_DATE('24/11/2022 22:00:00', 'dd/mm/yyyy hh24:mi:ss'), NULL, NULL);
INSERT INTO Match VALUES (DEFAULT, 28, 26, TO_DATE('28/11/2022 13:00:00', 'dd/mm/yyyy hh24:mi:ss'), NULL, NULL);
INSERT INTO Match VALUES (DEFAULT, 25, 27, TO_DATE('28/11/2022 19:00:00', 'dd/mm/yyyy hh24:mi:ss'), NULL, NULL);
INSERT INTO Match VALUES (DEFAULT, 26, 27, TO_DATE('02/12/2022 22:00:00', 'dd/mm/yyyy hh24:mi:ss'), NULL, NULL);
INSERT INTO Match VALUES (DEFAULT, 28, 25, TO_DATE('02/12/2022 22:00:00', 'dd/mm/yyyy hh24:mi:ss'), NULL, NULL);

INSERT INTO Match VALUES (DEFAULT, 31, 32, TO_DATE('24/11/2022 16:00:00', 'dd/mm/yyyy hh24:mi:ss'), NULL, NULL);
INSERT INTO Match VALUES (DEFAULT, 29, 30, TO_DATE('24/11/2022 19:00:00', 'dd/mm/yyyy hh24:mi:ss'), NULL, NULL);
INSERT INTO Match VALUES (DEFAULT, 32, 30, TO_DATE('28/11/2022 16:00:00', 'dd/mm/yyyy hh24:mi:ss'), NULL, NULL);
INSERT INTO Match VALUES (DEFAULT, 29, 31, TO_DATE('28/11/2022 22:00:00', 'dd/mm/yyyy hh24:mi:ss'), NULL, NULL);
INSERT INTO Match VALUES (DEFAULT, 30, 31, TO_DATE('02/12/2022 18:00:00', 'dd/mm/yyyy hh24:mi:ss'), NULL, NULL);
INSERT INTO Match VALUES (DEFAULT, 32, 29, TO_DATE('02/12/2022 18:00:00', 'dd/mm/yyyy hh24:mi:ss'), NULL, NULL);

INSERT INTO Match VALUES (DEFAULT, NULL, NULL, TO_DATE('03/12/2022 18:00:00', 'dd/mm/yyyy hh24:mi:ss'), NULL, NULL);
INSERT INTO Match VALUES (DEFAULT, NULL, NULL, TO_DATE('03/12/2022 22:00:00', 'dd/mm/yyyy hh24:mi:ss'), NULL, NULL);
INSERT INTO Match VALUES (DEFAULT, NULL, NULL, TO_DATE('04/12/2022 18:00:00', 'dd/mm/yyyy hh24:mi:ss'), NULL, NULL);
INSERT INTO Match VALUES (DEFAULT, NULL, NULL, TO_DATE('04/12/2022 22:00:00', 'dd/mm/yyyy hh24:mi:ss'), NULL, NULL);
INSERT INTO Match VALUES (DEFAULT, NULL, NULL, TO_DATE('05/12/2022 18:00:00', 'dd/mm/yyyy hh24:mi:ss'), NULL, NULL);
INSERT INTO Match VALUES (DEFAULT, NULL, NULL, TO_DATE('05/12/2022 22:00:00', 'dd/mm/yyyy hh24:mi:ss'), NULL, NULL);
INSERT INTO Match VALUES (DEFAULT, NULL, NULL, TO_DATE('06/12/2022 18:00:00', 'dd/mm/yyyy hh24:mi:ss'), NULL, NULL);
INSERT INTO Match VALUES (DEFAULT, NULL, NULL, TO_DATE('06/12/2022 22:00:00', 'dd/mm/yyyy hh24:mi:ss'), NULL, NULL);

INSERT INTO Match VALUES (DEFAULT, NULL, NULL, TO_DATE('09/12/2022 18:00:00', 'dd/mm/yyyy hh24:mi:ss'), NULL, NULL);
INSERT INTO Match VALUES (DEFAULT, NULL, NULL, TO_DATE('09/12/2022 22:00:00', 'dd/mm/yyyy hh24:mi:ss'), NULL, NULL);
INSERT INTO Match VALUES (DEFAULT, NULL, NULL, TO_DATE('10/12/2022 18:00:00', 'dd/mm/yyyy hh24:mi:ss'), NULL, NULL);
INSERT INTO Match VALUES (DEFAULT, NULL, NULL, TO_DATE('10/12/2022 22:00:00', 'dd/mm/yyyy hh24:mi:ss'), NULL, NULL);

INSERT INTO Match VALUES (DEFAULT, NULL, NULL, TO_DATE('13/12/2022 22:00:00', 'dd/mm/yyyy hh24:mi:ss'), NULL, NULL);
INSERT INTO Match VALUES (DEFAULT, NULL, NULL, TO_DATE('14/12/2022 22:00:00', 'dd/mm/yyyy hh24:mi:ss'), NULL, NULL);

INSERT INTO Match VALUES (DEFAULT, NULL, NULL, TO_DATE('17/12/2022 18:00:00', 'dd/mm/yyyy hh24:mi:ss'), NULL, NULL);
INSERT INTO Match VALUES (DEFAULT, NULL, NULL, TO_DATE('18/12/2022 18:00:00', 'dd/mm/yyyy hh24:mi:ss'), NULL, NULL);
